[0.019s] Invoking command in '/home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces': /usr/bin/cmake /home/kuanghaoze/d2lros2/game_ws/kuang_interfaces -DCMAKE_INSTALL_PREFIX=/home/kuanghaoze/d2lros2/game_ws/install/kuang_interfaces
[0.045s] -- Found ament_cmake: 1.3.5 (/opt/ros/humble/share/ament_cmake/cmake)
[0.272s] -- Found std_msgs: 4.2.3 (/opt/ros/humble/share/std_msgs/cmake)
[0.331s] -- Found rosidl_generator_c: 3.1.4 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.337s] -- Found rosidl_adapter: 3.1.4 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.345s] -- Found rosidl_generator_cpp: 3.1.4 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.359s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.380s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.463s] -- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.527s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.748s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.748s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[0.749s]   kuang_interfaces --arguments-file
[0.749s]   /home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces/rosidl_adapter__arguments__kuang_interfaces.json
[0.749s]   --output-dir
[0.749s]   /home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces/rosidl_adapter/kuang_interfaces
[0.749s]   --output-file
[0.750s]   /home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces/rosidl_adapter/kuang_interfaces.idls)
[0.750s]   returned error code 1:
[0.750s] 
[0.750s]   Error processing 'std_msgs/Float64 valueS' of 'kuang_interfaces/Kuangshi':
[0.750s]   ''valueS' is an invalid field name.  It should have the pattern
[0.751s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[0.751s] 
[0.751s]   Traceback (most recent call last):
[0.751s] 
[0.751s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.752s]       return _run_code(code, main_globals, None,
[0.752s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.752s]       exec(code, run_globals)
[0.752s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.752s]       sys.exit(main())
[0.753s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.753s]       abs_idl_file = convert_to_idl(
[0.753s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.753s]       return convert_msg_to_idl(
[0.753s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.754s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.754s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[0.754s]       fields.append(Field(
[0.754s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
[0.754s]       raise NameError(
[0.755s] 
[0.755s]   NameError: 'valueS' is an invalid field name.  It should have the pattern
[0.755s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[0.755s] 
[0.755s] Call Stack (most recent call first):
[0.756s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.756s]   CMakeLists.txt:20 (rosidl_generate_interfaces)
[0.756s] 
[0.756s] [0m
[0.756s] -- Configuring incomplete, errors occurred!
[0.757s] See also "/home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces/CMakeFiles/CMakeOutput.log".
[0.759s] Invoked command in '/home/kuanghaoze/d2lros2/game_ws/build/kuang_interfaces' returned '1': /usr/bin/cmake /home/kuanghaoze/d2lros2/game_ws/kuang_interfaces -DCMAKE_INSTALL_PREFIX=/home/kuanghaoze/d2lros2/game_ws/install/kuang_interfaces
